export const ALL_COURSE='/course/all';
export const GET_COURSES_BY_COURSECODE='/course/get-by-course-code';
export const BY_COURSE_NAME='/course/get-by-course-name';
export const BY_COURSE_CATEGORY='/course/get-by-course-category';
// export const MEDIA_BY_COURSECODE='/course/media/:courseCode'
export const ASSIGNED_COURSE='/course/assigned';
export const GET_LEARNER_LIST='/admin/get-all-learners';
export const MEMBER_REGISTER='/admin/member-register';
export const CREATE_COURSE='/admin/create-course';
export const ADMIN_SIGNIN='/admin/sign-in';
export const SIGN_IN='/sign-in';