export const HOME_PATH='/';
export const LOGIN_PATH='/login';
export const REGISTER_PATH="/register";
export const DASH_BOARD='/dashboard';
export  const ABOUT ='/about';
export const PROFILE='/user_profile';
export const CHANGE_PASSWORD='/change_password';
export const MY_COURSES='/my_courses';
export const UPLOAD_COURSES='/dashboard/upload_course';
export const COURSE_DETAIL='/dashboard/:course_id';
export const ADMIN='/admin';
export const ADMIN_LOGIN='/admin_login'